steps:
- name: gcr.io/cloud-builders/gsutil
  id: Prepare cache dir
  entrypoint: /bin/sh
  args:
  - -c
  - mkdir /workspace/cache

- name: gcr.io/cloud-builders/gsutil
  id: Restore cache
  args:
  - rsync
  - -r
  - gs://prototip-2-cache/cache/
  - /workspace/cache

- name: 'haskell:8.8.2'
  id: Test & Build
  entrypoint: /bin/sh
  args:
  - -c
  - |
      cd server && cabal update && cabal build
      && cabal test
      && cabal install --install-mehod=copy --installdir=/workspace
      && cp -r /builder/home/.cabal /workspace/cache

- name: gcr.io/cloud-builders/gsutil
  id: Store cache
  args:
  - rsync
  - -r
  - /workspace/cache/
  - gs://prototip-2-cache/cache

- name: gcr.io/cloud-builders/docker
  id: Build
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/prototip-2:$TAG_NAME'
  - '.'

- name: gcr.io/cloud-builders/docker
  id: Push
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/prototip-2:$TAG_NAME'
timeout: 1800s

