steps:

- name: gcr.io/cloud-builders/gsutil
  id: Restore cache
  args:
  - cp
  - gs://prototip-2-cache/cache.tar.gz
  - /workspace/cache.tar.gz

- name: 'haskell:8.8.2'
  id: Test & Build binary
  entrypoint: /bin/sh
  args:
  - -c
  - |
      tar xzf cache.tar.gz -C /builder/home/ \
      && cd server && cabal update && cabal build \
      && cabal test \
      && cabal install --install-method=copy --installdir=/workspace \
      && cd /builder/home && tar czf /workspace/cache.tar.gz .cabal/

- name: gcr.io/cloud-builders/gsutil
  id: Store cache
  args:
  - cp
  - /workspace/cache.tar.gz
  - gs://prototip-2-cache/cache.tar.gz

- name: gcr.io/cloud-builders/docker
  id: Build image
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/prototip-2:$TAG_NAME'
  - '.'

- name: gcr.io/cloud-builders/docker
  id: Push image
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/prototip-2:$TAG_NAME'

- name: gcr.io/$PROJECT_ID/kustomize
  id: Inject variables
  dir: kustomize
  args:
  - edit
  - set
  - image
  - 'prototip-2-image=gcr.io/$PROJECT_ID/prototip-2:$TAG_NAME'
  env:
  - CLOUDSDK_COMPUTE_ZONE=asia-northeast1-a
  - CLOUDSDK_CONTAINER_CLUSTER=prototip-2-cluster
  - GCLOUD_PROJECT=prototip-2

- name: gcr.io/$PROJECT_ID/kustomize
  id: Deploy
  args:
  - build
  - kustomize/
  env:
  - APPLY=true
  - CLOUDSDK_COMPUTE_ZONE=asia-northeast1-a
  - CLOUDSDK_CONTAINER_CLUSTER=prototip-2-cluster
  - GCLOUD_PROJECT=prototip-2

timeout: 2400s

