steps:
- name: 'haskell:8.8.2'
  id: Test
  entrypoint: /bin/sh
  args:
  - -c
  - 'cd server && stack test'

- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/prototip-2:$TAG_NAME'
  - '.'

- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/prototip-2:$TAG_NAME'

