steps:

- name: gcr.io/cloud-builders/gsutil
  id: Restore cache
  args:
  - cp
  - gs://prototip-2-cache/cabal.tar.gz
  - /workspace/cabal.tar.gz

- name: 'haskell:8.8.2'
  id: Test & Build binary
  entrypoint: /bin/sh
  args:
  - -c
  - |
      tar xzf cabal.tar.gz -C /builder/home/ &&\
      cd server && cabal update && cabal build &&\
      cabal test &&\
      cabal install --install-method=copy --installdir=/workspace &&\
      cd /builder/home && tar czf /workspace/cabal.tar.gz .cabal/

- name: gcr.io/cloud-builders/gsutil
  id: Store cache
  args:
  - cp
  - /workspace/cabal.tar.gz
  - gs://prototip-2-cache/cabal.tar.gz

- name: gcr.io/cloud-builders/yarn
  id: Install client modules
  dir: client
  args:
  - install

- name: gcr.io/cloud-builders/gsutil
  id: Restore node_modules
  dir: client
  entrypoint: /bin/sh
  args:
  - -c
  - |
      gsutil cp gs://prototip-2-cache/node_modules.tar.gz node_modules.tar.gz && \
      tar xzf node_modules.tar.gz

- name: gcr.io/cloud-builders/yarn
  id: Build client
  dir: client
  args:
  - webpack

- name: gcr.io/cloud-builders/gsutil
  id: Store node_modules
  dir: client
  entrypoint: /bin/sh
  args:
  - -c
  - |
      tar czf node_modules.tar.gz node_modules/ && \
      gsutil cp node_modules.tar.gz gs://prototip-2-cache/node_modules.tar.gz

- name: gcr.io/cloud-builders/docker
  id: Build docker image
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/prototip-2:$TAG_NAME'
  - '.'

- name: gcr.io/cloud-builders/docker
  id: Push docker image
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/prototip-2:$TAG_NAME'

- name: gcr.io/$PROJECT_ID/kustomize
  id: Inject variables to manifests
  dir: kustomize
  args:
  - edit
  - set
  - image
  - 'prototip-2-image=gcr.io/$PROJECT_ID/prototip-2:$TAG_NAME'
  env:
  - CLOUDSDK_COMPUTE_ZONE=asia-northeast1-a
  - CLOUDSDK_CONTAINER_CLUSTER=prototip-2-cluster
  - GCLOUD_PROJECT=prototip-2

- name: gcr.io/$PROJECT_ID/kustomize
  id: Deploy
  args:
  - build
  - kustomize/
  env:
  - APPLY=true
  - CLOUDSDK_COMPUTE_ZONE=asia-northeast1-a
  - CLOUDSDK_CONTAINER_CLUSTER=prototip-2-cluster
  - GCLOUD_PROJECT=prototip-2

timeout: 2400s

